title: Welcome
author: Anton Burenko
email: burenkoanton@gmail.com
description: >-
  Some of my art:)

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
